### ISSUE TITLE
Unnecessary scrollbars on your own live preview.

### ISSUE THREAD

**Issue by NickJorens** [creativetimofficial/ct-vue-black-dashboard-pro#1]
![image](https://user-images.githubusercontent.com/7328317/49875173-a6769d00-fe20-11e8-8039-da446cb9fc8e.png)

https://demos.creative-tim.com/vue-black-dashboard-pro/#/dashboard

**Comment by cristijora** [comment]
Hello @NickJorens Thanks a lot for reporting this. We did an update which should fix this issue. Apparently this was only present on Windows. 
Have a great beginning of the year!
