### ISSUE TITLE
Build issues on Netlify

### ISSUE THREAD

**Issue by dacarva** [creativetimofficial/ct-vue-black-dashboard-pro#10]
Hello, I just tried to deploy the out-of-the-box repository to Netlify to share it with my team and I am having issues on deployment. Here is the log file:

2:46:36 PM: Build ready to start
2:46:39 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
2:46:39 PM: build-image tag: v3.3.2
2:46:39 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
2:46:39 PM: Fetching cached dependencies
2:46:40 PM: Starting to download cache of 255.0KB
2:46:40 PM: Finished downloading cache in 111.705752ms
2:46:40 PM: Starting to extract cache
2:46:40 PM: Failed to fetch cache, continuing with build
2:46:40 PM: Starting to prepare the repo for build
2:46:40 PM: No cached dependencies found. Cloning fresh repo
2:46:40 PM: git clone https://github.com/dacarva/cannvest-investor-dashboard
2:46:41 PM: Preparing Git Reference refs/heads/master
2:46:42 PM: Starting build script
2:46:42 PM: Installing dependencies
2:46:44 PM: Downloading and installing node v10.16.3...
2:46:44 PM: Downloading https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.xz...
2:46:44 PM:      0.5%
2:46:44 PM: #
2:46:44 PM: #
2:46:44 PM: #
2:46:44 PM: #
2:46:44 PM: #################
2:46:44 PM:                                                      29
2:46:44 PM: .4%
2:46:45 PM: 
############################
2:46:45 PM: ##############################                81.9%
2:46:45 PM: 
########################################################################
2:46:45 PM: 100.0%
2:46:45 PM: Computing checksum with sha256sum
2:46:45 PM: Checksums matched!
2:46:49 PM: Now using node v10.16.3 (npm v6.9.0)
2:46:49 PM: Attempting ruby version 2.6.2, read from environment
2:46:51 PM: Using ruby version 2.6.2
2:46:51 PM: Using PHP version 5.6
2:46:51 PM: Started restoring cached node modules
2:46:51 PM: Finished restoring cached node modules
2:46:51 PM: Started restoring cached yarn cache
2:46:51 PM: Finished restoring cached yarn cache
2:46:51 PM: Installing yarn at version 1.17.0
2:46:51 PM: Installing Yarn!
2:46:51 PM: > Downloading tarball...
2:46:51 PM: [1/2]: https://
2:46:51 PM: yarnpkg.com/downloads/1.17.0/yarn-v1.17.0.tar.gz --> /tmp/yarn.tar.gz.kfMAFLUuxR
2:46:51 PM:   % Total    % Received % Xf
2:46:51 PM: erd  Average Speed   Time    Time     Time  Current
2:46:51 PM:                                  D
2:46:51 PM: load  Upload   Total   Spent    Left  Speed
2:46:51 PM: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2:46:52 PM: 
100    93  100    93    0     0    342
2:46:52 PM:      0 --:--:-- --:--:-- --:--:--   341
100    93  100    93    0     0    342      0 --:--:-- --:--:-- --:--:--   341
2:46:52 PM: 
100   609    0   609    0     0    923      0 --:--:-- --:--:-- --:--:--
2:46:52 PM: 923
2:46:53 PM: 
100 1213k  100 1213k    0     0  1081k
2:46:53 PM:       0  0:00:01  0:00:01 --:--:-- 1081k
2:46:53 PM: [2/2]: https://yarnpkg.
2:46:53 PM: com/downloads/1.17.0/yarn-v1.17.0.tar.gz.asc --> /tmp/yarn.tar.gz.kfMAF
2:46:53 PM: LUuxR.asc
2:46:53 PM: 
100    97  100    97
2:46:53 PM:    0     0   1621      0 --:--:-- --:--:-- --:--:--  1621
2:46:53 PM: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
2:46:53 PM:  --:--:--     0
100   613    0   613    0     0   3475      0 --:--:-- --:--:-- --:--:--  598k
2:46:53 PM: 
100   832  100   832    0     0   3896
2:46:53 PM:   0 --:--:-- --:--:-- --:--:--  3896
2:46:53 PM: > Verifying integrity...
2:46:53 PM: gpg: Signature made Fri 14 Jun 2019 06:55:58 PM UTC using RSA key ID 69475BAA
2:46:53 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
2:46:53 PM: gpg: WARNING: This key is not certified with a trusted signature!
2:46:53 PM: gpg:          There is no indication that the signature belongs to the owner.
2:46:53 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
2:46:53 PM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
2:46:53 PM: > GPG signature looks good
2:46:53 PM: > Extracting to ~/.yarn...
2:46:53 PM: > Adding to $PATH...
2:46:53 PM: > We've added the following to your /opt/buildhome/.profile
2:46:53 PM: > If this isn't the profile of your current shell then please add the following to your correct profile:
2:46:53 PM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
2:46:53 PM: 
2:46:54 PM: > Successfully installed Yarn 1.17.0! Please open another terminal where the `yarn` command will now be available.
2:46:54 PM: Installing NPM modules using Yarn version 1.17.0
2:46:55 PM: yarn install v1.17.0
2:46:55 PM: [1/4] Resolving packages...
2:46:56 PM: [2/4] Fetching packages...
2:47:22 PM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
2:47:22 PM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
2:47:22 PM: [3/4] Linking dependencies...
2:47:22 PM: warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
2:47:22 PM: warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
2:47:22 PM: warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
2:47:32 PM: [4/4] Building fresh packages...
2:47:36 PM: Done in 40.84s.
2:47:36 PM: NPM modules installed using Yarn
2:47:37 PM: Started restoring cached go cache
2:47:37 PM: Finished restoring cached go cache
2:47:37 PM: unset GOOS;
2:47:37 PM: unset GOARCH;
2:47:37 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
2:47:37 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
2:47:37 PM: go version >&2;
2:47:37 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
2:47:37 PM: go version go1.12 linux/amd64
2:47:37 PM: Installing missing commands
2:47:37 PM: Verify run directory
2:47:37 PM: Executing user command: npm run build
2:47:37 PM: > vue-black-dashboard-pro@1.0.0 build /opt/build/repo
2:47:37 PM: > vue-cli-service build
2:47:38 PM: -  Building for production...
2:47:41 PM:  ERROR  Failed to compile with 1 errors7:47:41 PM
2:47:41 PM: Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
2:47:41 PM: Thread Loader (Worker 0)
2:47:41 PM: No ESLint configuration found.
2:47:41 PM:     at PoolWorker.fromErrorObj (/opt/build/repo/node_modules/thread-loader/dist/WorkerPool.js:258:12)
2:47:41 PM:     at Config.getLocalConfigHierarchy (/opt/build/repo/node_modules/eslint/lib/config.js:255:39)
2:47:41 PM:     at Config.getConfigHierarchy (/opt/build/repo/node_modules/eslint/lib/config.js:179:43)
2:47:41 PM:     at Config.getConfigVector (/opt/build/repo/node_modules/eslint/lib/config.js:286:21)
2:47:41 PM:     at Config.getConfig (/opt/build/repo/node_modules/eslint/lib/config.js:329:29)
2:47:41 PM:     at processText (/opt/build/repo/node_modules/eslint/lib/cli-engine.js:163:33)
2:47:41 PM:     at CLIEngine.executeOnText (/opt/build/repo/node_modules/eslint/lib/cli-engine.js:620:17)
2:47:41 PM:     at lint (/opt/build/repo/node_modules/eslint-loader/index.js:263:17)
2:47:41 PM:     at transform (/opt/build/repo/node_modules/eslint-loader/index.js:237:18)
2:47:41 PM:     at /opt/build/repo/node_modules/loader-fs-cache/index.js:127:18
2:47:41 PM:     at ReadFileContext.callback (/opt/build/repo/node_modules/loader-fs-cache/index.js:31:14)
2:47:41 PM: You may use special comments to disable some warnings.
2:47:41 PM: Use // eslint-disable-next-line to ignore the next line.
2:47:41 PM: Use /* eslint-disable */ to ignore all warnings in a file.
2:47:41 PM:  ERROR  Build failed with errors.
2:47:41 PM: npm
2:47:41 PM:  ERR! code ELIFECYCLE
2:47:41 PM: npm
2:47:41 PM:  ERR! errno 1
2:47:41 PM: npm
2:47:41 PM: ERR! vue-black-dashboard-pro@1.0.0 build: `vue-cli-service build`
2:47:41 PM: npm ERR!
2:47:41 PM:  Exit status 1
2:47:41 PM: npm
2:47:41 PM: ERR!
2:47:41 PM: npm
2:47:41 PM: ERR! Failed at the vue-black-dashboard-pro@1.0.0 build script.
2:47:41 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2:47:41 PM: npm
2:47:41 PM:  ERR! A complete log of this run can be found in:
2:47:41 PM: npm ERR!     /opt/buildhome/.npm/_logs/2019-08-26T19_47_41_496Z-debug.log
2:47:41 PM: Skipping functions preparation step: no functions directory set
2:47:41 PM: Caching artifacts
2:47:41 PM: Started saving node modules
2:47:41 PM: Finished saving node modules
2:47:41 PM: Started saving yarn cache
2:47:41 PM: Finished saving yarn cache
2:47:41 PM: Started saving pip cache
2:47:41 PM: Finished saving pip cache
2:47:41 PM: Started saving emacs cask dependencies
2:47:41 PM: Finished saving emacs cask dependencies
2:47:41 PM: Started saving maven dependencies
2:47:41 PM: Finished saving maven dependencies
2:47:41 PM: Started saving boot dependencies
2:47:41 PM: Finished saving boot dependencies
2:47:41 PM: Started saving go dependencies
2:47:41 PM: Finished saving go dependencies
2:47:45 PM: Error running command: Build script returned non-zero exit code: 1
2:47:45 PM: Failing build: Failed to build site
2:47:45 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
2:47:45 PM: Finished processing build request in 1m6.169769032s

**Comment by cristijora** [comment]
Hey @dacarva Most likely it's because of the node version. Can you try to force Node 8.x
You can do so under Build & Deploy -> Environment 
![Screen Shot 2019-08-27 at 4 18 57 PM](https://user-images.githubusercontent.com/15955045/63774674-6d1a8a80-c8e6-11e9-8286-8c280e39acaa.png)

**Comment by cristijora** [comment]
Try adding the variable like I showed above. Not sure nvmrc works in Netlify. It's strange because I personally deployed this black dashboard configuration on netlify at least on 3 different projects.
Do you have anything else added custom in the project?
