### ISSUE TITLE
LACK OF SUPPORT AND UPDATES

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-black-dashboard-pro#26]
You have left your users behind, no answers, no fixes, no updates, no support, i am really disappointed, after buying 3 products, just never again!... be more serious and start fixing your products and making them better before you keep making new buggy products, leaving all other products with no support

**Comment by dragosct10** [comment]
Hi, @LaravDev! Thanks for using our products. We are sorry that you think this about us and we want to tell you that we had some internal problems with some of our vuejs products, but now everything is fine and like you see we already made an update to this product last week and also we will respond to our client's requests. We will update the vuejs products constantly from now on. Thanks for your understanding! 

Regards,
Dragos
