### ISSUE TITLE
Perfect Scrollbar not appearing when on Firefox 65.0 Win 10

### ISSUE THREAD

**Issue by ThePlasmaRailgun** [creativetimofficial/ct-vue-black-dashboard-pro#3]
The Perfect Scrollbar plugin is not appearing on Firefox 65.0, on Windows 10. This problem persists after all extensions have been disabled. 
![image](https://user-images.githubusercontent.com/16828772/52315428-16faef80-2974-11e9-972c-e0e685dfaa25.png)
I verified that the react version of the Black Dashboard Pro works. Please fix as I need to move to production soon.

**Comment by cristijora** [comment]
Hello @ThePlasmaRailgun 
Thanks for reporting!
Just fixed several issues on Internet Explorer + some windows specific issues including this one. We'll release an update this week.

**Comment by cristijora** [comment]
@ThePlasmaRailgun The updates were pushed (v1.1.1). You can simply re-download the archive from the website (Downloads section) and replace components/scss and layout files.
