### ISSUE TITLE
[Bug] Paginated table example search produces invisible results

### ISSUE THREAD

**Issue by jackof33trades** [creativetimofficial/ct-vue-black-dashboard-pro#33]
### Version
1.2.3
### Reproduction link
https://demos.creative-tim.com/vue-black-dashboard-pro/#/table-list/paginated
### Operating System
macOS Big Sur 11.3.1
### Device
laptop
### Browser & Version
Safari and Firefox. Both latest versions
### Steps to reproduce
1. Goto the demo link: https://demos.creative-tim.com/vue-black-dashboard-pro/#/table-list/paginated
2. enter a search parameter into the search-records field

note that as you type the number of rows matching search will be correct, but for some reason the results are invisible.
### What is expected?
for the data of the valid search results to be visible. The row exists, but you can't see the data.
### What is actually happening?
The correct number of rows display, but the actual data is invisible.

---
### Additional comments
This seems to be an issue with el-table from element-ui. I console logged the search results and traced it through each method, and the fuse search results are all coming back fine. For some reason el-table can't display the updated results.

**Comment by rarestoma** [comment]
Hi @jackof33trades,

Thank you for working with our products and for pointing us this issue. 

I did some tests and I found that it is working changing in package.json the `fuse.js` version with `^3.2.0`: `"fuse.js": "^3.2.0"`.

Can you please try it and let me know if it works?

Thank you,
Rares

**Comment by jackof33trades** [comment]
Hi,

Changing the version did fix the issue. Thank you!

**Comment by luthordev** [comment]
`watch: {
    searchQuery(value) {
      let result = this.tableData;
      if (value !== "") {
        result = [];
        this.fuseSearch.search(this.searchQuery).forEach((item) => {
          result.push(item.item);
        });
      }
      this.searchedData = result;
    },
  },`
