### ISSUE TITLE
notification issues

### ISSUE THREAD

**Issue by yunpeng-zhang** [creativetimofficial/ct-vue-black-dashboard-pro#5]
had set the notification to bottom right, need to

1. how to add timestamp to notification message and wrap lines
2. how to change the order of notification to show the latest message at bottom.

`      this.$notify({
        type: 'success',
        message: `Sidebar mini ${isMinimizedText}...`,
        icon: 'tim-icons icon-spaceship',
        verticalAlign: 'bottom',
        horizonalAlign: 'right',
      });`

**Comment by cristijora** [comment]
Hey @yunpeng-zhang Not sure I fully understood your questions but will try to respond:
1. You can add it to the `message` or `title`or if you want to add it for every notification you can change `Notification.vue` component and add a span/div after content-renderer (line 36)
2. For this, `Notification.vue` and the plugin file of the notification need some updates
```js
// Notification.vue Update the following computed
    customPosition() {
      let initialMargin = 20;
      let alertHeight = this.elmHeight + 10;
      let sameAlerts = this.$notifications.state.filter(alert => {
        return (
          alert.horizontalAlign === this.horizontalAlign &&
          alert.verticalAlign === this.verticalAlign
        );
      });
      let sameAlertsCount = 1
      let currentIndex = sameAlerts.findIndex(n => n.timestamp === this.timestamp)
      if (this.$notifications.settings.overlap) {
        sameAlertsCount = 1;
      }
      if (currentIndex !== -1) {
        sameAlertsCount = currentIndex + 1
      }
      let pixels = (sameAlertsCount - 1) * alertHeight + initialMargin;
      let styles = {};
      if (this.verticalAlign === 'top') {
        styles.top = `${pixels}px`;
      } else {
        styles.bottom = `${pixels}px`;
      }
      return styles;
    }

```
Inside `NotificationPlugin/index.js` change the settings part by adding a new setting
` order: 'reverse' // normal | reverse (When reverse, each notification will be added on top)`
And then change the `addNotification` method to this
```js
  addNotification(notification) {
    if (typeof notification === 'string' || notification instanceof String) {
      notification = { message: notification };
    }
    notification.timestamp = new Date();
    notification.timestamp.setMilliseconds(
      notification.timestamp.getMilliseconds() + this.state.length
    );
    notification = Object.assign({}, this.settings, notification);
    if (this.settings.order === 'reverse') {
      this.state.unshift(notification)
    } else {
      this.state.push(notification)
    }
  }
```

**Comment by cristijora** [comment]
This was also added as part of v1.2.2 so you can switch between notifications order
