### ISSUE TITLE
how to add badge to collapse-item title?

### ISSUE THREAD

**Issue by yunpeng-zhang** [creativetimofficial/ct-vue-black-dashboard-pro#7]
Hello, trying to implement the collapseItem using Vue Black Dashboard, how can I add badge to CollapseItem title area? As the title is defined in <collapse-time title="Title">, it is not straightforward to add the badge to the title. Adding badge outside of collapse-item will only show badges with the real content. 
![Capturebadge](https://user-images.githubusercontent.com/6248939/61989806-92c02580-b002-11e9-9706-7cba70754444.PNG)

**Comment by cristijora** [comment]
Do you want to add the badges near the title @yunpeng-zhang If yes, you can use the collapse item title slot
```
<template v-slot:title>
                <span class="mr-2">Collapsible Group Item #3</span>
                <Badge type="success">Some badge</Badge>
              </template>
```
![image](https://user-images.githubusercontent.com/15955045/63779008-88899380-c8ee-11e9-9eef-0aec41fd4ce2.png)
