### ISSUE TITLE
Fresh install vue warning

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-black-dashboard-pro#8]
Please check the image from the console...

<img width="402" alt="Screen Shot 2019-08-07 at 6 20 38 AM" src="https://user-images.githubusercontent.com/35145882/62622433-9180d980-b8db-11e9-9ccc-fbed167f163c.png">

Thanks in advance for your help

**Comment by cristijora** [comment]
Thanks for pointing out @LaravDev Issue was fixed and will be up with the next update.

**Comment by cristijora** [comment]
Resolved in latest version 1.2.2
